import { Playfair_Display, Lato } from "next/font/google";
import "./globals.css";

const playfair = Playfair_Display({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-playfair",
});

const lato = Lato({
  subsets: ["latin"],
  weight: ["400", "700", "900"],
  variable: "--font-lato",
});

export const metadata = {
  title: "Create sahil",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
     <html
      lang="en"
      className={`${playfair.variable} ${lato.variable}`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
